@startuml class
class controllers.auth
class controllers.bookings
class controllers.hotels
class controllers.users
class middleware.auth
class models.Booking
class models.Hotel
class models.User
class routes.auth
class routes.bookings
class routes.hotels
class routes.users
class server
class config.config
class config.db
server ..> config.config
server ..> config.db
server ..> routes.hotels
server ..> routes.auth
server ..> routes.bookings
server ..> routes.users
routes.auth ..> controllers.auth
routes.auth ..> middleware.auth
routes.bookings ..> controllers.bookings
routes.bookings ..> middleware.auth
routes.hotels ..> controllers.hotel
routes.hotels ..> routes.bookings
routes.hotels ..> middleware.auth
routes.users ..> controllers.users
routes.users ..> middleware.auth
middleware.auth ..> models.User
controllers.auth ..> models.User
controllers.bookings ..> models.Booking
controllers.bookings ..> models.Hotel
controllers.hotels ..> models.Hotel
controllers.users ..> models.User
@enduml