@startuml sequence
title Get all hotels
skinparam actorStyle Hollow
actor user
participant server
control router
control controller
entity models
database MongoDB as db
collections data
user -> server : GET /api/v1/bookings/:id
server -> router : bookings
router -> controller : protect
controller -> controller : getBooking
controller -> models : Booking.findById(:id)
models -> db : db.bookings.find({_id: :id})
db -> data : query
db <-- data : booking
models <-- db : booking
controller <-- models : booking
user <-- controller : booking
@enduml