@startuml sequence
title New booking
skinparam actorStyle Hollow
actor user
participant server
control router
control controller
entity models
database MongoDB as db
collections data
user -> server : PUT /api/v1/bookings
server -> router : bookings
router -> controller : protect
controller -> controller : addBooking
controller -> models : Booking.create(req.body)
models -> db : db.bookings.insertOne(req.body)
db -> data : document
db <-- data : booking
models <-- db : booking
controller <-- models : booking
user <-- controller : booking
@enduml