@startuml sequence
title Get all bookings
skinparam actorStyle Hollow
actor user
participant server
control router
control controller
entity models
database MongoDB as db
collections data
user -> server : GET /api/v1/bookings
server -> router : bookings
router -> controller : protect
controller -> controller : getBookings
alt role: user
controller -> models : Booking.find({user: req.user.id})
models -> db : db.bookings.find({user: req.user.id})
else role: admin
controller -> models : Booking.find()
models -> db : db.bookings.find()
end
db -> data : query
db <-- data : bookings
models <-- db : bookings
controller <-- models : bookings
user <-- controller : bookings
@enduml