@startuml sequence
title Edit booking
skinparam actorStyle Hollow
actor user
participant server
control router
control controller
entity models
database MongoDB as db
collections data
user -> server : PUT /api/v1/bookings/:id
server -> router : bookings/:id
router -> controller : protect
controller -> controller : updateBooking
controller -> models : Booking.findByIdAndUpdate(:id, req.body)
models -> db : db.bookings.findOneAndUpdate({_id: :id}, req.body)
db -> data : update
db <-- data : booking
models <-- db : booking
controller <-- models : booking
user <-- controller : booking
@enduml